name: Deploy ðŸŒŒ

on:
    push:
        branches:
            - main

env:
    CONTAINER_REGISTRY: ghcr.io
    IMAGE_NAME: panpipe-team/backend-web-api

jobs:
    push-to-registry:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4.2.2

            - name: Login to Github Registry ðŸ”
              uses: docker/login-action@v3.3.0
              with:
                registry: ${{ env.CONTAINER_REGISTRY }}
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push Docker image ðŸ§± && ðŸš€
              uses: docker/build-push-action@v6
              with:
                tags: ${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:latest
                push: true
    
    deploy:
        needs: push-to-registry
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4.2.2

            - name: Create .env file ðŸ¤«
              run: |
                echo "Generating .env file"

                echo "# Autogenerated .env file" > .env
                echo "CONTAINER_REGISTRY=${{ env.CONTAINER_REGISTRY }}" >> .env
                echo "IMAGE_NAME=${{ env.IMAGE_NAME }}" >> .env
                echo "WEB_API_PORT=${{ secrets.WEB_API_PORT }}" >> .env

            - name: Copy docker-compose and .env files to server via scp ðŸ“¥
              uses: appleboy/scp-action@v0.1.7
              with:
                host: ${{ secrets.SSH_HOST }}
                username: ${{ secrets.SSH_USERNAME }}
                port: ${{ secrets.SSH_PORT }}
                key: ${{ secrets.SSH_KEY }}
                source: "./docker-compose.yml,./.env"
                target: "${{ secrets.REMOTE_APP_DIRECTORY }}/new-files"
            
            - name: Reup docker compose via ssh ðŸ”„
              uses: appleboy/ssh-action@v1.0.3
              env:
                GHCR_USERNAME: ${{ github.actor }}
                GHCR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                REMOTE_APP_DIRECTORY: ${{ secrets.REMOTE_APP_DIRECTORY }}
              with:
                host: ${{ secrets.SSH_HOST }}
                username: ${{ secrets.SSH_USERNAME }}
                port: ${{ secrets.SSH_PORT }}
                key: ${{ secrets.SSH_KEY }}
                envs: GHCR_USERNAME,GHCR_TOKEN,REMOTE_APP_DIRECTORY
                script: |
                  cd $REMOTE_APP_DIRECTORY
                  docker compose down
                  mv -t . ./new-files/docker-compose.yml ./new-files/.env
                  echo $GHCR_TOKEN | docker login ghcr.io -u $GHCR_USERNAME --password-stdin
                  docker compose pull
                  docker compose up -d
